version: '3.1'
services:
    mini-crawler:
        image: timtosi/mcrawler:latest
        cap_drop:
            - ALL
        entrypoint:
            - /mcrawler
        command:
            - "localhost:8080"
        hostname: mcrawler
